### ISSUE TITLE
QueryDeveloperDisk ImagePresent always "False"

### ISSUE THREAD

**Issue by bandy101** [exaphaser/MK.MobileDevice#1]
as the title

**Comment by 0xFireball** [comment]
I have not been seeing this issue. Could you please post your code, and if possible, more information about your usage and device? This works fine on my devices; it works by asking the image mounter service if an image is present.

**Comment by 0xFireball** [comment]
I am closing this issue because it seems to be a non-issue (I have not been able to reproduce the bug). If this is actually an issue, please post a new issue and provide details as to the nature of the bug and possibly steps to duplicate it.
