### ISSUE TITLE
iPhoneXE

### ISSUE THREAD

**Issue by Freudy007** [exaphaser/MK.MobileDevice#2]
Hello,

I can connect to Iphone with iPhone(), read / write files from / to phone.

But I can't connect to Iphone with iPhoneXE(..). (I want play with the files and folders of the applications)

Can you help me please, with peace of start code ?

**Comment by 0xFireball** [comment]
iPhoneXE is an incomplete interface with the iExplorer program. iTMDiPhone and iPhone provide all the functionality you should need. If I am missing something, let me know.
