### ISSUE TITLE
How can I open the share folder of an application?

### ISSUE THREAD

**Issue by dun82** [exaphaser/MK.MobileDevice#5]
I tried to connect through ConnectViaHouseArrest() but failed to get the folder directories using GetDirectories("/Documents"), any idea? Thanks!

**Comment by 0xFireball** [comment]
Hello,
@dun82 , Apple in their stupidity (or as they like to believe, their "infinite wisdom") removed this feature in iOS 8.3. I spent quite a bit of time experimenting with it but it looks like it really is broken. For confirmation, just take a look at all the tools like iFunBox or iMazing. Only certain applications that specifically allow access to their data sandbox can be accessed since iOS 8.3. Sorry about that. If you can find a way to work around it, please share it and pull request. This is the most advanced  open source library for its purpose right now, so contributions would be much appreciated,

**Comment by dun82** [comment]
Thank you for quick reply. How about if I want the shared folder of the App only? Just wanna copy the save file created by my application.

**Comment by 0xFireball** [comment]
Right. I planned on implementing that earlier, but saw no point in doing so because it wasn't supported unless the app explicitly allowed it since iOS 8.3. If your app supports it and you are sure iTunes can access the app directory, I can add the feature for you.

**Comment by dun82** [comment]
As long as I enable the flag "UIFileSharingEnabled", using iTunes can always access the shared folder of my App, i.e. /Documents in the specific App container. Thank you so much for your help.

**Comment by 0xFireball** [comment]
Are you going to implement it yourself or want me to do it?

**Comment by dun82** [comment]
Appreciated if you can enhance that for us and I have no idea about extracting the shared folder.

**Comment by dun82** [comment]
I tried to create new ha client and send command to "VendContainer", still not success to get the app sharing folder... May be I overlook the libimobiledevice... Any clues on that?

**Comment by 0xFireball** [comment]
Is your app (not the iPhone app, the desktop app) open source? Perhaps I could look at that to find out what you need and help you.

**Comment by 0xFireball** [comment]
Also, thank you so much for trying with Libimobiledevice! What exactly went wrong with VendContainer?

**Comment by 0xFireball** [comment]
Did you try VendDocuments? Also here's the current code: https://github.com/exaphaser/MK.MobileDevice/blob/master/MobileDevice/iPhone.cs#L912

**Comment by dun82** [comment]
I tried both VenderDocuments and VendContainer, no good. Especially I don't start house arrest service but create a new HA client, I can successfully create the client until the HA get result throws an error tag in the plist... 

The routine ConnectViaHouseArrest, all passed, until I call GetDirectories, exception throws

My App just save the text file in the Document folder, with the file sharing flag TRUE and I can see the text file from iTunes, iTools, iExplorer.. 
My device is iPad Mini with iOS 8.1

Seems iTools owns something special...

**Comment by dun82** [comment]
I got it! 
In ConnectViaHouseArrest, comment the line HouseArrest.house_arrest_client_free(hHA); will have everything normal! 

Just need to properly handle before disconnecting the device!

**Comment by 0xFireball** [comment]
You are amazing, thanks! Could you make a pull request?

**Comment by 0xFireball** [comment]
I updated the code.
https://github.com/exaphaser/MK.MobileDevice/commit/ddd8b7ae5e610211efc9f517c622cf9773e96343
Thanks for helping!
